---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*

Gemspec/RequireMFA:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
